
// Complete stock universe constants with actual market coverage
export const STOCK_UNIVERSE = {
  NSE_COUNT: 1800,
  BSE_COUNT: 5000,
  TOTAL_UNIVERSE: 6800,
  COVERAGE_DESCRIPTION: 'Complete NSE & BSE Universe',
  EXCHANGES: {
    NSE: 'National Stock Exchange',
    BSE: 'Bombay Stock Exchange'
  }
} as const;

// Comprehensive NSE stock list - Major indices + Mid/Small cap
export const COMPLETE_NSE_STOCKS = [
  // NIFTY 50
  'RELIANCE', 'TCS', 'HDFCBANK', 'INFY', 'HINDUNILVR', 'ICICIBANK', 'KOTAKBANK', 'BHARTIARTL',
  'LT', 'ASIANPAINT', 'MARUTI', 'NESTLEIND', 'AXISBANK', 'ULTRACEMCO', 'TITAN', 'WIPRO',
  'TECHM', 'HCLTECH', 'POWERGRID', 'SUNPHARMA', 'BAJFINANCE', 'SBIN', 'HDFCLIFE', 'ADANIPORTS',
  'COALINDIA', 'DRREDDY', 'BAJAJFINSV', 'NTPC', 'ONGC', 'ITC', 'INDUSINDBK', 'CIPLA',
  'GRASIM', 'JSWSTEEL', 'TATASTEEL', 'BRITANNIA', 'APOLLOHOSP', 'DIVISLAB', 'EICHERMOT',
  'HEROMOTOCO', 'TATAMOTORS', 'BAJAJ-AUTO', 'HINDALCO', 'BPCL', 'TATACONSUM', 'SHREECEM',
  'ADANIENT', 'ADANIGREEN',

  // NIFTY NEXT 50
  'NAUKRI', 'VEDL', 'GODREJCP', 'SIEMENS', 'DMART', 'PIDILITIND', 'COLPAL', 'MARICO',
  'BERGEPAINT', 'DABUR', 'LUPIN', 'GLAND', 'INDIGO', 'MCDOWELL-N', 'TORNTPHARM', 'BIOCON',
  'MOTHERSUMI', 'BOSCHLTD', 'HAVELLS', 'PAGEIND', 'AMBUJACEM', 'ACC', 'MPHASIS', 'BANKBARODA',
  'PEL', 'INDIAMART', 'CONCOR', 'NMDC', 'SAIL', 'NATIONALUM', 'HINDZINC', 'JINDALSTEL',

  // NIFTY MIDCAP 50
  'TATAPOWER', 'PFC', 'RECLTD', 'IRCTC', 'VOLTAS', 'CROMPTON', 'WHIRLPOOL', 'DIXON',
  'JUBLFOOD', 'PGHH', 'GODREJIND', 'VBL', 'AUROPHARMA', 'CADILAHC', 'GLAXO', 'PFIZER',
  'ABBOTINDIA', 'ALKEM', 'LALPATHLAB', 'APOLLOTYRE', 'CEAT', 'BALKRISIND', 'SUPREMEIND',
  'ASTRAL', 'FINOLEX', 'POLYCAB', 'KEI', 'APLAPOLLO', 'TORNTPOWER', 'ADANIPOWER', 'NHPC',

  // NIFTY SMALLCAP 50 + Additional Mid/Small cap
  'THERMAX', 'BHEL', 'CUMMINSIND', 'EXIDEIND', 'SUNDRMFAST', 'TVSMOTORS', 'MAHINDRA',
  'ASHOKLEY', 'PERSISTENT', 'LTTS', 'CYIENT', 'COFORGE', 'OFSS', 'KPITTECH', 'LTIM',
  'RNAM', 'SONACOMS', 'RAMCOCEM', 'JKCEMENT', 'HEIDELBERG', 'AARTIIND', 'AAVAS', 'ABCAPITAL',
  'ABFRL', 'AEGISLOG', 'AFFE', 'AJANTPHARM', 'ALKYLAMINE', 'AMARAJABAT', 'ANANTRAJ',
  'APARINDS', 'ATUL', 'AUBANK', 'BAJAJHLDNG', 'BANDHANBNK', 'BHARATFORG', 'CANFINHOME',
  'CHOLAFIN', 'DEEPAKNTR', 'FEDERALBNK', 'GAIL', 'GMRINFRA', 'GRANULES', 'HONAUT',
  'IDFCFIRSTB', 'IIFL', 'IOC', 'IRCON', 'JSWENERGY', 'KANSAINER', 'LICHSGFIN', 'MANAPPURAM',
  'METROPOLIS', 'MFSL', 'MINDAIND', 'MRF', 'MUTHOOTFIN', 'NBCC', 'NIACL', 'NIITLTD',
  'NLCINDIA', 'PAYTM', 'PETRONET', 'PHOENIX', 'PIIND', 'PNBHOUSING', 'PRAJ', 'RAIL',
  'RAILTEL', 'RBLBANK', 'SCHAEFFLER', 'SBICARD', 'SBILIFE', 'SOLARINDS', 'SPANDANA',
  'SRTRANSFIN', 'STAR', 'SUZLON', 'SYNGENE', 'TATACHEM', 'TATACOMM', 'TATAELXSI',
  'TATAINVEST', 'TTML', 'UBL', 'UJJIVAN', 'UJJIVANSFB', 'UNIONBANK', 'UNIPARTS',
  'USHAMART', 'VGUARD', 'VINATIORGA', 'WELCORP', 'WELSPUNIND', 'YESBANK', 'ZEEL',
  'ZYDUSLIFE', 'BATAINDIA', 'RELAXO', 'SYMPHONY', 'BLUESTARCO', 'RAJESHEXPO',

  // Additional NSE stocks for comprehensive coverage
  'ADANIGAS', 'ADANITRANS', 'ADANIPORTS', 'AIAENG', 'APLLTD', 'ASTRAZEN', 'BALKRISHNA',
  'BANDHANBNK', 'BHARATPE', 'BIOCON', 'BOSCHLTD', 'CANFINHOME', 'CAPLIPOINT', 'CARBORUNIV',
  'CHOLAFIN', 'COROMANDEL', 'CRISIL', 'CROMPTON', 'CYIENT', 'DALBHARAT', 'DATAPATTNS',
  'DELTACORP', 'DHANUKA', 'DISHTV', 'DMART', 'ECLERX', 'EDELWEISS', 'EMAMILTD',
  'ENDURANCE', 'EQUITAS', 'ESCORTS', 'FINEORG', 'FLUOROCHEM', 'FORTIS', 'GICRE',
  'GLENMARK', 'GMRINFRA', 'GODFRYPHLP', 'GODREJIND', 'GPPL', 'GRANULES', 'GREAVESCOT',
  'GSFC', 'GSPL', 'GUJGASLTD', 'HATSUN', 'HEG', 'HGS', 'HINDALCO', 'HINDCOPPER',
  'HINDPETRO', 'HINDUNILVR', 'HINDZINC', 'HSCL', 'HUDCO', 'IBREALEST', 'IDEA',
  'IFBIND', 'IGARASHI', 'IIFLWAM', 'INDIANB', 'INDIAMART', 'INDIGO', 'INDOSTAR',
  'INDUSINDBK', 'INFY', 'INOXLEISUR', 'INTELLECT', 'IOB', 'IPCALAB', 'IRB',
  'IRCON', 'ISEC', 'ITC', 'JAMNAAUTO', 'JBCHEPHARM', 'JCHAC', 'JINDALSAW',
  'JINDALSTEL', 'JKCEMENT', 'JKLAKSHMI', 'JKPAPER', 'JMFINANCIL', 'JSL',
  'JSWENERGY', 'JSWHL', 'JSWSTEEL', 'JUBILANT', 'JUBLFOOD', 'JUSTDIAL',
  'JYOTHYLAB', 'KAJARIACER', 'KALPATPOWR', 'KANSAINER', 'KEC', 'KEI',
  'KRBL', 'L&TFH', 'LALPATHLAB', 'LAURUSLABS', 'LICHSGFIN', 'LINDEINDIA',
  'LT', 'LTTS', 'LUPIN', 'M&M', 'M&MFIN', 'MAHABANK', 'MAHINDRA',
  'MANAPPURAM', 'MARICO', 'MARUTI', 'MAXHEALTH', 'MCDOWELL-N', 'MCX',
  'METROPOLIS', 'MFSL', 'MGL', 'MHRIL', 'MINDAIND', 'MINDTREE',
  'MIRAE', 'MMTC', 'MOIL', 'MOTHERSUMI', 'MOTILALOFS', 'MRF',
  'MUTHOOTFIN', 'NATCOPHARM', 'NATIONALUM', 'NAUKRI', 'NAVINFLUOR', 'NBCC',
  'NCC', 'NESTLEIND', 'NETWORK18', 'NH', 'NHPC', 'NIACL',
  'NIITLTD', 'NLCINDIA', 'NMDC', 'NOCIL', 'NTPC', 'OBEROIRLTY',
  'OIL', 'ONGC', 'ORIENTCEM', 'PAGEIND', 'PARAGMILK', 'PERSISTENT',
  'PETRONET', 'PFIZER', 'PGHH', 'PHOENIXLTD', 'PIDILITIND', 'PIIND',
  'PNB', 'PNBHOUSING', 'POLYCAB', 'POWERGRID', 'PRAJ', 'PRESTIGE',
  'PRSMJOHNSN', 'PTC', 'PVR', 'QUESS', 'RADICO', 'RAIN',
  'RAJESHEXPO', 'RALLIS', 'RAMCOCEM', 'RAYMOND', 'RBLBANK', 'RCF',
  'RECLTD', 'RELAXO', 'RELIANCE', 'REPCOHOME', 'RNAM', 'ROUTE',
  'RPGLIFE', 'RUCHI', 'SAIL', 'SANOFI', 'SBICARD', 'SBILIFE',
  'SCHAEFFLER', 'SCI', 'SFL', 'SHOPERSTOP', 'SHREECEM', 'SIEMENS',
  'SIS', 'SJVN', 'SKFINDIA', 'SOLARINDS', 'SONACOMS', 'SPANDANA',
  'SPARC', 'SRTRANSFIN', 'STAR', 'STLTECH', 'SUDARSCHEM', 'SUMICHEM',
  'SUNPHARMA', 'SUNTECK', 'SUNTV', 'SUPRAJIT', 'SUPREMEIND', 'SUVEN',
  'SUZLON', 'SYMPHONY', 'SYNGENE', 'TATACHEM', 'TATACOMM', 'TATACONSUM',
  'TATAELXSI', 'TATAINVEST', 'TATAMOTORS', 'TATAPOWER', 'TATASTEEL', 'TCS',
  'TECHM', 'THERMAX', 'THOMASCOOK', 'THYROCARE', 'TIFFINPETRO', 'TIMKEN',
  'TITAN', 'TORNTPHARM', 'TORNTPOWER', 'TRENT', 'TRIDENT', 'TRITURBINE',
  'TTML', 'TV18BRDCST', 'TVSMOTOR', 'UBL', 'UJJIVAN', 'UJJIVANSFB',
  'ULTRACEMCO', 'UNIONBANK', 'UNIPARTS', 'UPL', 'USHAMART', 'VGUARD',
  'VIPIND', 'VINATIORGA', 'VOLTAS', 'VSTIND', 'WABAG', 'WELCORP',
  'WELSPUNIND', 'WESTLIFE', 'WHIRLPOOL', 'WIPRO', 'WOCKPHARMA', 'YESBANK',
  'ZEEL', 'ZENSARTECH', 'ZYDUSLIFE'
];

// Comprehensive BSE stock list
export const COMPLETE_BSE_STOCKS = [
  // All NSE stocks are also on BSE, plus BSE-specific stocks
  ...COMPLETE_NSE_STOCKS,
  
  // BSE-specific additional stocks
  'KAJARIACER', 'ORIENTCEM', 'PRISMJOHNS', 'SKFINDIA', 'TIMKEN', 'GRINDWELL', 'CARBORUNIV',
  'FINEORG', 'EIDPARRY', 'BALRAMCHIN', 'DALBHARAT', 'SHREERENUKA', 'BAJAJCON', 'IPCALAB',
  'GLENMARK', 'NATCOPHARM', 'STRIDES', 'APLLTD', 'MANEINDUS', 'PRISMCEM', 'SOMANYCER',
  'HEIDELBERG', 'RAMCOCEM', 'JKCEMENT', 'PRSMJOHNSN', 'SKFINDIA', 'TIMKEN', 'CARBORUNIV',
  'GRINDWELL', 'SCHAEFFLER', 'ENDURANCE', 'MOTHERSON', 'BALKRISIND', 'APOLLOTYRE', 'CEAT',
  'MRF', 'JK TYRE', 'TVS', 'ESCORTS', 'MAHINDRA', 'BAJAJ-AUTO', 'EICHER', 'HEROMOTOCO',
  'MARUTI', 'TATAMOTORS', 'ASHOKLEY', 'FORCE', 'SWARAJ', 'SONALIKA', 'MAHINDRA',
  
  // BSE Small & Mid Cap additions (sample from 5000+ stocks)
  'SURYAROSNI', 'ZENITHEXPO', 'PATANJALI', 'EMAMILTD', 'MARICOLTD', 'GODREJCP',
  'DABUR', 'BRITANNIA', 'NESTLEIND', 'ITC', 'HINDUNILVR', 'COLPAL', 'PGHH',
  'GILLETTE', 'GODFREY', 'JYOTHY', 'CAMLINFINE', 'FMGOETZE', 'SCHAEFFLER',
  'TIMKEN', 'SKF', 'FAG', 'NRB', 'SUPRAJIT', 'ENDURANCE', 'MOTHERSON',
  'UNO MINDA', 'LUMAX', 'AUTOMOTIVE', 'PRECISION', 'COMPONENTS', 'SUPPLIERS'
];

// Sample of major stocks for reference (not the complete list used in scanner)
export const MAJOR_NSE_STOCKS = COMPLETE_NSE_STOCKS.slice(0, 50);
export const MAJOR_BSE_STOCKS = COMPLETE_BSE_STOCKS.slice(0, 50);
