
// Complete stock universe constants with comprehensive market coverage
export const STOCK_UNIVERSE = {
  NSE_COUNT: 2000,
  BSE_COUNT: 5500,
  TOTAL_UNIVERSE: 7500,
  COVERAGE_DESCRIPTION: 'Complete NSE & BSE Universe',
  EXCHANGES: {
    NSE: 'National Stock Exchange',
    BSE: 'Bombay Stock Exchange'
  }
} as const;

// Comprehensive NSE stock list - All major stocks
export const COMPREHENSIVE_NSE_STOCKS = [
  // NIFTY 50
  'RELIANCE', 'TCS', 'HDFCBANK', 'INFY', 'HINDUNILVR', 'ICICIBANK', 'KOTAKBANK', 'BHARTIARTL',
  'LT', 'ASIANPAINT', 'MARUTI', 'NESTLEIND', 'AXISBANK', 'ULTRACEMCO', 'TITAN', 'WIPRO',
  'TECHM', 'HCLTECH', 'POWERGRID', 'SUNPHARMA', 'BAJFINANCE', 'SBIN', 'HDFCLIFE', 'ADANIPORTS',
  'COALINDIA', 'DRREDDY', 'BAJAJFINSV', 'NTPC', 'ONGC', 'ITC', 'INDUSINDBK', 'CIPLA',
  'GRASIM', 'JSWSTEEL', 'TATASTEEL', 'BRITANNIA', 'APOLLOHOSP', 'DIVISLAB', 'EICHERMOT',
  'HEROMOTOCO', 'TATAMOTORS', 'BAJAJ-AUTO', 'HINDALCO', 'BPCL', 'TATACONSUM', 'SHREECEM',
  'ADANIENT', 'ADANIGREEN', 'NAUKRI', 'VEDL',

  // NIFTY NEXT 50 + Major Mid/Small Cap
  'GODREJCP', 'SIEMENS', 'DMART', 'PIDILITIND', 'COLPAL', 'MARICO', 'BERGEPAINT', 'DABUR',
  'LUPIN', 'GLAND', 'INDIGO', 'MCDOWELL-N', 'TORNTPHARM', 'BIOCON', 'MOTHERSUMI', 'BOSCHLTD',
  'HAVELLS', 'PAGEIND', 'AMBUJACEM', 'ACC', 'MPHASIS', 'BANKBARODA', 'PEL', 'INDIAMART',
  'CONCOR', 'NMDC', 'SAIL', 'NATIONALUM', 'HINDZINC', 'JINDALSTEL', 'TATAPOWER', 'PFC',
  'RECLTD', 'IRCTC', 'VOLTAS', 'CROMPTON', 'WHIRLPOOL', 'DIXON', 'JUBLFOOD', 'PGHH',

  // Additional NSE Large Cap
  'GODREJIND', 'VBL', 'AUROPHARMA', 'CADILAHC', 'GLAXO', 'PFIZER', 'ABBOTINDIA', 'ALKEM',
  'LALPATHLAB', 'APOLLOTYRE', 'CEAT', 'BALKRISIND', 'SUPREMEIND', 'ASTRAL', 'FINOLEX',
  'POLYCAB', 'KEI', 'APLAPOLLO', 'TORNTPOWER', 'ADANIPOWER', 'NHPC', 'THERMAX', 'BHEL',
  'CUMMINSIND', 'EXIDEIND', 'SUNDRMFAST', 'TVSMOTORS', 'MAHINDRA', 'ASHOKLEY', 'PERSISTENT',
  'LTTS', 'CYIENT', 'COFORGE', 'OFSS', 'KPITTECH', 'LTIM', 'RNAM', 'SONACOMS',

  // Additional Mid Cap NSE
  'RAMCOCEM', 'JKCEMENT', 'HEIDELBERG', 'AARTIIND', 'AAVAS', 'ABCAPITAL', 'ABFRL', 'AEGISLOG',
  'AFFLE', 'AJANTPHARM', 'ALKYLAMINE', 'AMARAJABAT', 'ANANTRAJ', 'APARINDS', 'ATUL', 'AUBANK',
  'BAJAJHLDNG', 'BANDHANBNK', 'BHARATFORG', 'CANFINHOME', 'CHOLAFIN', 'DEEPAKNTR', 'FEDERALBNK',
  'GAIL', 'GMRINFRA', 'GRANULES', 'HONAUT', 'IDFCFIRSTB', 'IIFL', 'IOC', 'IRCON',
  'JSWENERGY', 'KANSAINER', 'LICHSGFIN', 'MANAPPURAM', 'METROPOLIS', 'MFSL', 'MINDAIND', 'MRF',
  'MUTHOOTFIN', 'NBCC', 'NIACL', 'NIITLTD', 'NLCINDIA', 'PAYTM', 'PETRONET', 'PHOENIX',

  // Small Cap NSE (High Quality)
  'PIIND', 'PNBHOUSING', 'PRAJ', 'RAIL', 'RAILTEL', 'RBLBANK', 'SCHAEFFLER', 'SBICARD',
  'SBILIFE', 'SOLARINDS', 'SPANDANA', 'SRTRANSFIN', 'STAR', 'SUZLON', 'SYNGENE', 'TATACHEM',
  'TATACOMM', 'TATAELXSI', 'TATAINVEST', 'TTML', 'UBL', 'UJJIVAN', 'UJJIVANSFB', 'UNIONBANK',
  'UNIPARTS', 'USHAMART', 'VGUARD', 'VINATIORGA', 'WELCORP', 'WELSPUNIND', 'YESBANK', 'ZEEL',
  'ZYDUSLIFE', 'BATAINDIA', 'RELAXO', 'SYMPHONY', 'BLUESTARCO', 'RAJESHEXPO', 'ADANIGAS',
  'ADANITRANS', 'AIAENG', 'APLLTD', 'ASTRAZEN', 'BALKRISHNA', 'BHARATPE', 'CAPLIPOINT',
  'CARBORUNIV', 'COROMANDEL', 'CRISIL', 'DALBHARAT', 'DATAPATTNS', 'DELTACORP', 'DHANUKA',

  // Additional Quality Stocks
  'DISHTV', 'ECLERX', 'EDELWEISS', 'EMAMILTD', 'ENDURANCE', 'EQUITAS', 'ESCORTS', 'FINEORG',
  'FLUOROCHEM', 'FORTIS', 'GICRE', 'GLENMARK', 'GODFRYPHLP', 'GPPL', 'GREAVESCOT', 'GSFC',
  'GSPL', 'GUJGASLTD', 'HATSUN', 'HEG', 'HGS', 'HINDCOPPER', 'HINDPETRO', 'HSCL',
  'HUDCO', 'IBREALEST', 'IDEA', 'IFBIND', 'IGARASHI', 'IIFLWAM', 'INDIANB', 'INDOSTAR',
  'INOXLEISUR', 'INTELLECT', 'IOB', 'IPCALAB', 'IRB', 'ISEC', 'JAMNAAUTO', 'JBCHEPHARM',
  'JCHAC', 'JINDALSAW', 'JKLAKSHMI', 'JKPAPER', 'JMFINANCIL', 'JSL', 'JSWHL', 'JUBILANT',
  'JUSTDIAL', 'JYOTHYLAB', 'KAJARIACER', 'KALPATPOWR', 'KRBL', 'LANDT', 'LAURUSLABS',
  'LINDEINDIA', 'MAXHEALTH', 'MCX', 'MGL', 'MHRIL', 'MINDTREE', 'MIRAE', 'MMTC',
  'MOIL', 'MOTILALOFS', 'NATCOPHARM', 'NAVINFLUOR', 'NCC', 'NETWORK18', 'NH', 'NOCIL',
  'OBEROIRLTY', 'OIL', 'ORIENTCEM', 'PARAGMILK', 'PHOENIXLTD', 'PNB', 'PTC', 'PVR',
  'QUESS', 'RADICO', 'RAIN', 'RALLIS', 'RAYMOND', 'RCF', 'REPCOHOME', 'ROUTE',
  'RPGLIFE', 'RUCHI', 'SANOFI', 'SCI', 'SFL', 'SHOPERSTOP', 'SIS', 'SJVN',
  'SKFINDIA', 'STLTECH', 'SUDARSCHEM', 'SUMICHEM', 'SUNTECK', 'SUNTV', 'SUPRAJIT', 'SUVEN',
  'TATAINVEST', 'THOMASCOOK', 'THYROCARE', 'TIFFINPETRO', 'TIMKEN', 'TRENT', 'TRIDENT',
  'TRITURBINE', 'TV18BRDCST', 'TVSMOTOR', 'VSTIND', 'WABAG', 'WESTLIFE', 'WOCKPHARMA',
  'ZENSARTECH'
];

// Comprehensive BSE stock list
export const COMPREHENSIVE_BSE_STOCKS = [
  // All NSE stocks are also on BSE
  ...COMPREHENSIVE_NSE_STOCKS,
  
  // BSE-specific additional stocks
  'KAJARIACER', 'ORIENTCEM', 'PRISMJOHNS', 'GRINDWELL', 'EIDPARRY', 'BALRAMCHIN', 'SHREERENUKA',
  'BAJAJCON', 'NATCOPHARM', 'STRIDES', 'MANEINDUS', 'PRISMCEM', 'SOMANYCER', 'FMGOETZE',
  'NRB', 'SUPRAJIT', 'UNO', 'LUMAX', 'AUTOMOTIVE', 'PRECISION', 'COMPONENTS', 'SUPPLIERS',
  'CAMLINFINE', 'GILLETTE', 'GODFREY', 'JYOTHY', 'PATANJALI', 'ZENITHEXPO', 'SURYAROSNI',
  'EMAMILTD', 'MARICOLTD', 'FORCE', 'SWARAJ', 'SONALIKA', 'EICHER', 'JK', 'TVS',
  'ESCORTS', 'APOLLOTYRE', 'CEAT', 'MRF', 'TYRE', 'BALKRISIND', 'MOTHERSON', 'ENDURANCE',
  'SCHAEFFLER', 'TIMKEN', 'CARBORUNIV', 'GRINDWELL', 'SKF', 'FAG', 'NRB', 'SUPRAJIT'
];

// Major stocks for quick scanning (top liquid stocks)
export const MAJOR_NSE_STOCKS = COMPREHENSIVE_NSE_STOCKS.slice(0, 100);
export const MAJOR_BSE_STOCKS = COMPREHENSIVE_BSE_STOCKS.slice(0, 100);
